export const products = [
    {
        id: 1,
        img: "https://i.imgur.com/OEObCSA.png",
        link: "https://bitbucket.org/rayansyed/valu/src/main/",
        video: "https://dl.dropboxusercontent.com/s/w7e89p1z0j5f0y0/capstoneVideo_Trim.mp4?dl=0",
        title: "Valorant University",
        subheading: "iOS App",
        features:"Creating AR Assets, Implementing various AR Experiences to help users learn quickly, Built the achievement list which allows users to earn in app rewards, Developed the news page which informs users with latest updates made to the app and the game, Worked with cloud Firestore for storing and retrieving data, Designed the home page and various other UI elements",
        date: "September 2021-December 2021",
        desc: "Valorant University is a companion app for the popular competitive FPS Valorant. This app allows new and experienced player learn new strategies through tutorials uploaded by the community, augmented reality training, and the ability to hire professional coaches. This app was built for iOS devices using Swift and SwiftUI. Augmented reality was implemented using Reality Composer. User authentication and data storage was handled using Firebase Firestore.",
    },
    {
        id: 2,
        img: "https://i.imgur.com/1e9MVPY.png",
        link: "http://lama.dev",
        video: "https://dl.dropboxusercontent.com/s/o3tdps18bcn7a0b/2022-01-21%2000-53-07_Trim.mp4?dl=0",
        title: "Black Mentorship Inc",
        subheading: "Prototype App",
        features:"Created user personas to better understand what the goals and charateristics of the end user would be, Created user journey maps to understand a users experiene with the current solution, Designed a Prototype applicatoin using Figma, Conducted usability tests to see the effectiveness of the solution",
        date: "May 2021-August 2021",
        desc: "The Black Mentorship INC mobile application is a prototype app designed using Figma. The goal of the project was to design a product for BMI that would help elevate their company to make the youth mentorship experience more effective. This application was designed by myself and 3 team members part of the Innovation Accelerator Program at Sheridan College. We competed with a number of other teams to deliver the best solution for BMI. By the end of the term our team was able to edge out the rest of the competiton and come out on top.",
    },
    {
        id: 3,
        img: "https://i.imgur.com/n9wtyH7.png",
        link: "http://lama.dev",
        video: "https://dl.dropboxusercontent.com/s/yurx109nzlcos62/2022-01-21%2001-02-07.mp4?dl=0",
        title: "&Beyond",
        subheading: "Website",
        features:"Build the application using ReactJS, Implement Firestore for storing data, Create a custom CMS allowing for changes to be made easily by other team members,",
        date: "In Progress",
        desc: "&Beyond is an experimental project in legitimizing the field of real-time video game photography.",
    },
    
]